name: seoul
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^0.29.3
  shared_preferences: ^0.5.12+4
  liquid_swipe: ^1.5.0
  soundpool: ^1.1.3
  uuid: ^2.2.2
  # audioplayers: ^0.17.3




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides:
  image: 2.0.7


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    # - assets/images/boxer/first page one.png
    # - assets/images/boxer/first page-2 two.png
    - assets/images/boxer/punch-left.png
    - assets/audio/bgm.ogg
    - assets/audio/swish-1.ogg
    - assets/audio/swish-2.ogg
    - assets/audio/swish-3.ogg
    - assets/audio/swish-4.ogg
    - assets/audio/swish-5.ogg
    - assets/audio/swish-6.ogg
    - assets/audio/swish-7.ogg
    - assets/audio/swish-8.ogg
    - assets/audio/swish-9.ogg
    - assets/audio/swish-10.ogg
    - assets/audio/swish-11.ogg
    - assets/audio/swish-12.ogg
    - assets/audio/swish-13.ogg
    - assets/images/background.png
    - assets/images/boxer/dizzy.png
    - assets/images/boxer/idle.png
    - assets/images/boxer/punch-left.png
    - assets/images/boxer/punch-right.png
    - assets/images/boxer/punch-up.png
    - assets/images/markers.png
    - assets/images/perfect-time.png
    - assets/images/title.png

   

 
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
